name: proyecto
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+11
  firebase_database: ^9.0.9
  firebase_storage: ^10.2.10
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/mascota.jpg
    - images/logo.jpg

